source('../../share/sysFacLib.R')

dat1a=clean.s2()
dat1b=clean.s5()
dat2a=clean.s8()
dat2b=clean.s7()

mic1a=doEmpiricalPlot(dat1a,plot=F)
mic1b=doEmpiricalPlot(dat1b,plot=F)
mic2a=doEmpiricalPlot(dat2a,plot=F)
mic2b=doEmpiricalPlot(dat2b,plot=F)
out1a=doBayes(dat1a,r.mean=.15,r.indv=.10,my.iter=50000)
out1b=doBayes(dat1b,r.mean=.15,r.indv=.10,my.iter=50000)
out2a=doBayes(dat2a,r.mean=.15,r.indv=.10,my.iter=50000)
out2b=doBayes(dat2b,r.mean=.15,r.indv=.10,my.iter=50000)

save.image(file='bayesTemp.RData')

#load('bayesTemp.RData')
source('../../share/sysFacLib.R')
pdf('figMod.pdf',width=10,height=10)
inRange=c(-.150,.150)
par(mfrow=c(2,2),mar=c(4,4,1,1),mgp=c(2,.7,0),cex=1.2)
doEstimatePlot(mic1a,out1a$mcmc,inRange)
mtext(side=3,cex=1.3,adj=0,"A.")
mtext(side=3,cex=1.2,adj=.1,line=-1,"Expt. 1A, Screwheads / Perceptual")
par(xpd=NA)
legend(20,-.055,legend=(c('Observed','Model')),title="Estimates",bg="antiquewhite",pch=21,pt.bg=c("white","red"),lty=2:1)
par(xpd=FALSE)
doEstimatePlot(mic1b,out1b$mcmc,inRange)
mtext(side=3,cex=1.3,adj=0,"B.")
mtext(side=3,cex=1.2,adj=.1,line=-1,"Expt. 1B, Screwheads / Memory")
doEstimatePlot(mic2a,out2a$mcmc,inRange)
mtext(side=3,cex=1.3,adj=0,"C.")
mtext(side=3,cex=1.2,adj=.1,line=-1,"Expt. 2A, Digits / Perceptual")
doEstimatePlot(mic2b,out2b$mcmc,inRange)
mtext(side=3,cex=1.3,adj=0,"D.")
mtext(side=3,cex=1.2,adj=.1,line=-1,"Expt. 2B, Digits / Memory")
dev.off()
